example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import tambah_barang ,show_wishlist_ajax ,show_wishlist, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit', tambah_barang, name='tambah_barang'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Muhammad Nabiel Andityo',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)
    
@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    context = {
        'nama': 'Muhammad Nabiel Andityo',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) 
            response.set_cookie('last_login', str(datetime.datetime.now())) 
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response
    
@login_required(login_url='/wishlist/login/')
def tambah_barang(request):
    if request.method == "POST":
        nama_barang = request.POST['nama_barang']
        harga_barang = request.POST['harga_barang']
        deskripsi = request.POST['deskripsi']
        barang_baru = BarangWishlist.objects.create(nama_barang=nama_barang, harga_barang=harga_barang, deskripsi=deskripsi)
        return JsonResponse({'error': False, 'msg':'Successful'})
    return redirect('wishlist:show_wishlist_ajax')

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
<!doctype html>
<html lang="en">
    
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  
  <body>
	
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
	
    <div class="container py-5">
        <div class = "login">

            <h1 class="form mb-2">Sign-in</h1>
        
            <form method="POST" action="">
                {% csrf_token %}
                <table>
                    <tr>
                        <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                    </tr>
                            
                    <tr>
                        <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                    </tr>
        
                    <tr>
                        <td><input class="btn btn-outline-success mt-3 mb-3" type="submit" value="Login">
                    </tr>
                </table>
            </form>  
                
            <p> Don't have an account? <a href="{% url 'wishlist:register' %}">Create account</a> </p>
            
            {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                      </div>
                    {% endfor %}
            {% endif %}   
            
        </div>
        
    </div>

    </body>

</html>

<style>
    body {
        background-color: white;
        text-align: center;
    }
    .container {
		background-color: #ADD8E6;
		align-items: center;
		width: 40%;
        height: 60%;
		padding: 10px;
        display: block;
        margin-top: 5%;
		border-radius: 25px;
    }
    .login {
        text-align: center;
    }
    table {
        margin-left: auto;
        margin-right: auto;
        margin-top: 20px;
    }
    tr {
        height: 50px;
</style>

wishlist/templates/register.html
<!doctype html>
<html lang="en">
    
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Registrasi Akun</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  
  <body>
	
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
	
    <div class="container py-5">
		<div class = "login">
			
			<h1>Sign-up</h1>  

				<form method="POST" >  
					{% csrf_token %}  
					<table>  
						{{ form.as_table }}  
						<tr>  
							<td></td>
							<td><input class="btn btn-outline-success mt-3 mb-3" type="submit" value="Register">
						</tr>  
					</table>  
				</form>

			{% if messages %}  
				<ul>   
					{% for message in messages %}  
						<li>{{ message }}</li>  
						{% endfor %}  
				</ul>   
			{% endif %}

		</div> 

    </body>

</html>

<style>
    body {
        background-color: white;
        text-align: center;
    }
    .container {
		background-color: #ADD8E6;
		align-items: center;
		width: 50%;
        height: 60%;
		padding: 10px;
        display: block;
        margin-top: 5%;
		border-radius: 25px;
    }
    table {
        margin-left: auto;
        margin-right: auto;
        margin-top: 20px;
    }
    tr {
        height: 50px;
</style>

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Wishlist</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<body>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

	<nav class="navbar navbar-expand-lg navbar-info bg-info">
	  <div class="container-fluid">
		<a class="navbar-brand" href="https://id.wikipedia.org/wiki/Fakultas_Ilmu_Komputer_Universitas_Indonesia">
			<img src="https://upload.wikimedia.org/wikipedia/id/thumb/c/c3/Makara_of_Fasilkom_UI.svg/1200px-Makara_of_Fasilkom_UI.svg.png" width="80" height="30" alt="">
		</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<form action="{% url "wishlist:show_wishlist_ajax" %}" >
			<button class="btn btn-success me-3 navbar-btn" type="submit" name="create-task">
				Add
			</button>
		</form>
		<div class="nav-item dropdown">
		  <ul class="navbar-nav">
			<li class="nav-item dropdown">
			  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
				Menu
			  </a>
			  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
				<li><a class="dropdown-item" href="{% url 'wishlist:show_xml' %}">XML</a></li>
				<li><a class="dropdown-item" href="{% url 'wishlist:show_json' %}">JSON</a></li>
				<li><a class="dropdown-item" href="{% url 'wishlist:logout' %}">Logout</a></li>
			  </ul>
			</li>
		  </ul>
		</div>
	  </div>
	</nav>

	<h5>Nama: <span style="font-weight:normal"><font size="4">{{nama}}</font></span></h5>
	<h5>Angkatan: <span style="font-weight:normal"><font size="4">2021</font></span></h5>

	<table class="table table-striped table-bordered">
		<thead class="table-danger">
			<tr>
			<th>Nama Barang</th>
			<th>Harga Barang</th>
			<th>Deskripsi</th>
		</thead>
		</tr>
		{% comment %} Tambahkan data di bawah baris ini {% endcomment %}
		{% for barang in list_barang %}
		<tr>
			<td>{{barang.nama_barang}}</td>
			<td>{{barang.harga_barang}}</td>
			<td>{{barang.deskripsi}}</td>
		</tr>
		{% endfor %}
	</table>
	<p>Sesi terakhir login: {{ last_login }}</p>
</body>
{% endblock content %}
    

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Add Wishlist</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<script>
    $(document).ready(function(){
        $.getJSON("{% url 'wishlist:show_json' %}", function(json) {
            var tables = [];
            $.each(json, function(index, val){
                var row = [];
                var fields = val.fields
                row.push("<td>" + String(val.fields.nama_barang) + "</td>");
                row.push("<td>" + val.fields.harga_barang + "</td>");
                row.push("<td>" + val.fields.deskripsi + "</td>");
                tables.push("<tr>" + row.join("") + "</tr>");
            });
            document.getElementById("list_barang").innerHTML = tables.join("");
        });

        $("#tambah_barang_form").submit(function(e){
            e.preventDefault();
            $(".btnClick").prop('disabled', true);
            $(".btnClick").text('Processing');
            var $form = $(this);
            var serializedData = $form.serialize();
            $.ajax({
                url: "{% url 'wishlist:tambah_barang' %}",
                type: "POST",
                data: serializedData,
                dataType: 'text',
                success: function (data) {
                    $(".btnClick").prop('disabled', false);
                    $(".btnClick").text('Submit');
                    $.getJSON("{% url 'wishlist:show_json' %}", function(json) {
                        var tables = [];
                        $.each(json, function(index, val){
                            var row = [];
                            var fields = val.fields
                            row.push("<td>" + String(val.fields.nama_barang) + "</td>");
                            row.push("<td>" + val.fields.harga_barang + "</td>");
                            row.push("<td>" + val.fields.deskripsi + "</td>");
                            tables.push("<tr>" + row.join("") + "</tr>");
                        });
                        document.getElementById("list_barang").innerHTML = tables.join("");
                    });

                }
              });
        });
    });

</script>

<nav class="navbar navbar-expand-lg navbar-info bg-info">
  <div class="container-fluid">
	<a class="navbar-brand" href="#">{{ nama }}</a>
	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
	  <span class="navbar-toggler-icon"></span>
	</button>
	<div class="nav-item dropdown">
	  <ul class="navbar-nav">
		<li class="nav-item dropdown">
		  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
			Menu
		  </a>
		  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
			<li><a class="dropdown-item" href="{% url 'wishlist:show_wishlist' %}">Main Page</a></li>
			<li><a class="dropdown-item" href="{% url 'wishlist:logout' %}">Logout</a></li>
		  </ul>
		</li>
	  </ul>
	</div>
  </div>
</nav>
	
<br>
<div class="container" >
    <form class="mb-5" method="POST" name="barang_form" id="tambah_barang_form">
        {% csrf_token %}
        <fieldset>
            <legend>Tambah Barang Wishlist</legend>
            <input class="form-control mb-3" type="text" placeholder="Nama barang" name="nama_barang">
            <input class="form-control mb-3" type="number" min="1" step="any" placeholder="Harga barang" name="harga_barang">
            <textarea class="form-control mb-3" rows="3" placeholder="Deskripsi" name="deskripsi"></textarea>
            <button type="submit" class="btn btn-primary btnClick">Submit</button>
        </fieldset>
    </form>

    <table class="table table-bordered" style="background-color: #e3f2fd;">
        <thead class="table-dark">
            <tr>
                <th scope="col">Nama Barang</th>
                <th scope="col">Harga Barang</th>
                <th scope="col">Deskripsi</th>
            </tr>
        </thead>
        <tbody id="list_barang">
        </tbody>
    </table>
    <p>Sesi terakhir login: {{ last_login }}<p>
</div>

{% endblock content %}